(()=>{
  'use strict';
  const state={sessionId:(crypto.randomUUID?.()||`visit-${Date.now()}-${Math.random().toString(36).slice(2)}`),viewed:new Set(),fit:0,opened:false,submitted:false};
  const css=`#ncSurveyButton{position:fixed;right:18px;bottom:18px;z-index:80;border:1px solid rgba(255,255,255,.22);border-radius:999px;padding:11px 16px;background:#d7b25d;color:#151006;font-weight:800;cursor:pointer;box-shadow:0 12px 32px rgba(0,0,0,.35)}#ncSurvey{position:fixed;inset:0;z-index:100;display:none;place-items:center;background:rgba(1,5,15,.78);padding:18px}#ncSurvey.open{display:grid}#ncSurvey .box{width:min(580px,100%);max-height:90vh;overflow:auto;background:#0b1d40;color:#f7f9ff;border:1px solid rgba(255,255,255,.16);border-radius:18px;padding:22px;box-shadow:0 28px 90px rgba(0,0,0,.55)}#ncSurvey h2{font:400 1.7rem Georgia,serif;margin:0 0 8px}#ncSurvey p{color:#aebbd2}#ncSurvey fieldset{border:0;padding:0;margin:18px 0}#ncSurvey legend{font-weight:800;margin-bottom:8px}#ncSurvey label{display:block;padding:7px 0}#ncSurvey textarea{width:100%;min-height:95px;background:#07152f;color:white;border:1px solid rgba(255,255,255,.18);border-radius:9px;padding:10px}#ncSurvey .actions{display:flex;gap:9px;justify-content:flex-end;flex-wrap:wrap}#ncSurvey button{border:0;border-radius:8px;padding:10px 15px;font-weight:800;cursor:pointer}.ncPrimary{background:#64d8ff;color:#07152f}.ncGhost{background:rgba(255,255,255,.08);color:white;border:1px solid rgba(255,255,255,.14)!important}.ncMessage{min-height:20px;color:#74e0a7}`;
  document.head.append(Object.assign(document.createElement('style'),{textContent:css}));
  const button=Object.assign(document.createElement('button'),{id:'ncSurveyButton',type:'button',textContent:'Share Your Experience'});
  const modal=document.createElement('div');modal.id='ncSurvey';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.innerHTML=`<form class="box"><h2>Help improve NAT-CORP</h2><p>This optional three-question survey does not require an account and does not save your Business Intake profile.</p><fieldset><legend>1. Did NAT-CORP help you discover relevant opportunities?</legend><label><input required type="radio" name="relevance" value="very_relevant"> Yes, very relevant</label><label><input type="radio" name="relevance" value="somewhat_relevant"> Somewhat relevant</label><label><input type="radio" name="relevance" value="not_relevant"> Not relevant</label></fieldset><fieldset><legend>2. How would you rate today’s experience?</legend><label><input required type="radio" name="experience" value="excellent"> Excellent</label><label><input type="radio" name="experience" value="good"> Good</label><label><input type="radio" name="experience" value="fair"> Fair</label><label><input type="radio" name="experience" value="poor"> Poor</label></fieldset><fieldset><legend>3. What is the one improvement you would most like to see?</legend><textarea name="improvement" maxlength="2000" placeholder="Your recommendation"></textarea></fieldset><div class="ncMessage" aria-live="polite"></div><div class="actions"><button class="ncGhost" type="button" data-close>Not now</button><button class="ncPrimary" type="submit">Submit feedback</button></div></form>`;
  document.body.append(button,modal);
  const open=()=>{if(state.submitted)return;state.opened=true;modal.classList.add('open');modal.querySelector('input')?.focus()};
  const close=()=>modal.classList.remove('open');
  button.addEventListener('click',open);modal.addEventListener('click',e=>{if(e.target===modal||e.target.closest('[data-close]'))close()});
  document.addEventListener('click',e=>{const card=e.target.closest?.('.card');if(card){const key=card.querySelector('h3')?.textContent||String(state.viewed.size+1);state.viewed.add(key)}const label=(e.target.textContent||'').toLowerCase();if(label.includes('analyze fit'))state.fit+=1;if(label.includes('start a new visit')&&!state.submitted)setTimeout(open,0)},true);
  modal.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();const form=new FormData(e.currentTarget),msg=modal.querySelector('.ncMessage'),submit=e.currentTarget.querySelector('[type=submit]');submit.disabled=true;msg.textContent='Submitting…';try{const r=await fetch('/api/natcorp-feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({session_id:state.sessionId,relevance_rating:form.get('relevance'),experience_rating:form.get('experience'),improvement_comment:form.get('improvement'),opportunities_viewed:state.viewed.size,analyze_fit_count:state.fit,completed_stage:'dashboard'})});const d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);state.submitted=true;msg.textContent='Thank you. Your feedback was recorded.';button.remove();setTimeout(close,1200)}catch(err){msg.textContent=err.message||'Feedback could not be submitted.';submit.disabled=false}});
  setTimeout(()=>{if(!state.submitted&&!state.opened)button.animate([{transform:'translateY(0)'},{transform:'translateY(-6px)'},{transform:'translateY(0)'}],{duration:700})},45000);
})();
